Silence lint for auto-generated Protobuf code
Since Rust 1.78, we see the following errors while building our code:

    error: unnecessary qualification
    Error:   --> src/../proto/metadata.rs:32:15
    |
    32 |     pub salt: ::std::vec::Vec<u8>,
    |               ^^^^^^^^^^^^^^^^^^^
    |
    note: the lint level is defined here
    --> src/lib.rs:36:5
    |
    36 |     unused_qualifications,
    |     ^^^^^^^^^^^^^^^^^^^^^
    help: remove the unnecessary path segments
    |
    32 -     pub salt: ::std::vec::Vec<u8>,
    32 +     pub salt: Vec<u8>,

These errors have to do with the auto-generated code from .proto files.
It seems that even latest releases of the Protobuf codegen crate output
code that is rejected by this lint.

Since we don't have control over the auto-generated code, silence this
lint for this module specifically.