Bump dialoguer dependency to v0.8.0
Bump the dependency of 'dialoguer' to v0.8.0, because the previous
version depended on a yanked version of the 'zeroize' crate. This threw
the following error:

    error: failed to select a version for the requirement `zeroize = "^0.9.3"`
    Error: candidate versions found which didn't match: 1.3.0, 1.2.0, 1.1.1, ...
    location searched: crates.io index
    required by package `dialoguer v0.7.0`
        ... which is depended on by `tindercrypt v0.3.0 (/home/runner/work/tindercrypt/tindercrypt)`
    Error: The process '/usr/share/rust/.cargo/bin/cargo' failed with exit code 101