Remove redundant imports
We have some nightly Rust errors, because some of our imports are
redundant. E.g.:

    error: the item `ring` is imported redundantly
    Error:   --> src/cryptors.rs:14:5
    |
    14 | use ring;
    |     ^^^^ the item `ring` is already defined here

Remove them to appease the builder.